version: '3'
services:
  web:
    build: ./
    command: rails server -b 0.0.0.0
    ports:
      - "3000:3000"

    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:latest


    environment:
      # - POSTGRES_NAME=rails
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
      # - POSTGRES_DB=course_catalog_development2
      # - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # named volume
